$ErrorActionPreference = 'Stop'
Write-Host 'Dorah Dental Patient App setup' -ForegroundColor Cyan
Write-Host ''
Write-Host '1. Open this folder in PowerShell:'
Write-Host '   cd mobile_patient_app'
Write-Host ''
Write-Host '2. Create the standard Android/iOS Flutter project files:'
Write-Host '   flutter create . --org com.dorahdental --project-name dorah_dental_patient'
Write-Host ''
Write-Host '3. Restore the app files from this package if flutter create replaced them.'
Write-Host '4. Run:'
Write-Host '   flutter pub get'
Write-Host '   dart pub global activate flutterfire_cli'
Write-Host '   flutterfire configure'
Write-Host ''
Write-Host '5. Set your Django API URL when running:'
Write-Host '   flutter run --dart-define=DORAH_API_URL=https://YOUR-DOMAIN/api'
Write-Host ''
Write-Host 'For local Android emulator:'
Write-Host '   flutter run --dart-define=DORAH_API_URL=http://10.0.2.2:8000/api'
Write-Host ''
Write-Host 'For a physical phone, use the PC LAN IP, for example:'
Write-Host '   flutter run --dart-define=DORAH_API_URL=http://192.168.1.10:8000/api'
