// Generated by FlutterFire CLI in the final Firebase setup step.
// Run: flutterfire configure
// Do not put Firebase service-account credentials in this file.
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('Web is not part of this patient mobile build.');
    }
    throw UnsupportedError('Firebase is not configured yet. Run flutterfire configure.');
  }
}
