# Generated by Django 5.1.2 on 2026-10-04 12:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_invoice_type_and_booked_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentEditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited_by', models.CharField(blank=True, max_length=150)),
                ('edited_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('old_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('new_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('old_payment_date', models.DateField(blank=True, null=True)),
                ('new_payment_date', models.DateField(blank=True, null=True)),
                ('old_payment_method', models.CharField(blank=True, max_length=50)),
                ('new_payment_method', models.CharField(blank=True, max_length=50)),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edit_logs', to='billing.payment')),
            ],
            options={
                'ordering': ['-edited_at'],
            },
        ),
    ]
