# Generated by Django 5.1.2 on 2026-08-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile_last_otp_sent_userprofile_otp_attempts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default="Dora's Dental Gem", max_length=200)),
                ('business_short_name', models.CharField(default="Dora's Dental", max_length=100)),
                ('tagline', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(default='+256 700 000 000', max_length=20)),
                ('email', models.EmailField(default='info@dorasdentalgem.com', max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
                ('address', models.TextField(default='Kampala, Uganda')),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('monday_hours', models.CharField(blank=True, max_length=100, null=True)),
                ('tuesday_hours', models.CharField(blank=True, max_length=100, null=True)),
                ('wednesday_hours', models.CharField(blank=True, max_length=100, null=True)),
                ('thursday_hours', models.CharField(blank=True, max_length=100, null=True)),
                ('friday_hours', models.CharField(blank=True, max_length=100, null=True)),
                ('saturday_hours', models.CharField(blank=True, max_length=100, null=True)),
                ('sunday_hours', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('currency', models.CharField(default='UGX', max_length=10)),
                ('currency_symbol', models.CharField(default='UGX', max_length=5)),
                ('timezone', models.CharField(default='Africa/Nairobi', max_length=50)),
                ('country', models.CharField(default='Uganda', max_length=100)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_prefix', models.CharField(default='INV-', max_length=10)),
                ('invoice_footer', models.TextField(blank=True, null=True)),
                ('notification_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('notification_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Settings',
                'verbose_name_plural': 'Company Settings',
            },
        ),
    ]
