# Generated by Django 5.1.2 on 2026-09-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userprofile_otp_verified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='otp_code',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
