import 'package:flutter/material.dart';
import '../services/api_service.dart';
import 'login_screen.dart';
import 'notifications_screen.dart';
import 'messages_screen.dart';

class HomeScreen extends StatefulWidget { const HomeScreen({super.key}); @override State<HomeScreen> createState()=>_HomeScreenState(); }
class _HomeScreenState extends State<HomeScreen> {
  late Future<Map<String,dynamic>> future;
  @override void initState(){super.initState();future=ApiService.dashboard();}
  void refresh(){setState(()=>future=ApiService.dashboard());}
  @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:Row(children:[Image.asset('assets/dental_logo.png',height:36),const SizedBox(width:10),const Text('Dorah Dental',style:TextStyle(fontWeight:FontWeight.bold))]),actions:[IconButton(onPressed:refresh,icon:const Icon(Icons.refresh)),IconButton(onPressed:()async{await ApiService.logout();if(mounted)Navigator.of(context).pushAndRemoveUntil(MaterialPageRoute(builder:(_)=>const LoginScreen()),(_)=>false);},icon:const Icon(Icons.logout))]),body:FutureBuilder(future:future,builder:(context,snap){if(snap.connectionState==ConnectionState.waiting)return const Center(child:CircularProgressIndicator());if(snap.hasError)return Center(child:Text('Unable to load your portal\n${snap.error}',textAlign:TextAlign.center));final d=snap.data!;final p=ApiService.patient??{};return RefreshIndicator(onRefresh:()async=>refresh(),child:ListView(padding:const EdgeInsets.all(18),children:[Text('Hello, ${p['name']??'Patient'}',style:const TextStyle(fontSize:25,fontWeight:FontWeight.w800,color:Color(0xFF123B52))),const SizedBox(height:4),const Text('Here is your dental care overview.',style:TextStyle(color:Colors.black54)),const SizedBox(height:20),_balance(d),const SizedBox(height:14),_appointment(d),const SizedBox(height:14),Row(children:[Expanded(child:_action(Icons.notifications_outlined,'Notifications',()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const NotificationsScreen())))),const SizedBox(width:12),Expanded(child:_action(Icons.chat_bubble_outline,'Messages',()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const MessagesScreen()))))]),const SizedBox(height:20),_section('Recent activity',d['recent_notifications']),]));});
  Widget _balance(Map d)=>Card(child:Padding(padding:const EdgeInsets.all(20),child:Row(children:[Container(width:52,height:52,decoration:BoxDecoration(color:const Color(0xFFE6F4F7),borderRadius:BorderRadius.circular(16)),child:const Icon(Icons.account_balance_wallet_outlined,color:Color(0xFF1A5276))),const SizedBox(width:15),Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Current balance',style:TextStyle(color:Colors.black54)),Text('UGX ${d['balance']??'0'}',style:const TextStyle(fontSize:24,fontWeight:FontWeight.w800,color:Color(0xFF1A5276)))])])));
  Widget _appointment(Map d){final a=d['next_appointment'];return Card(child:Padding(padding:const EdgeInsets.all(20),child:a==null?const Row(children:[Icon(Icons.event_available_outlined,color:Color(0xFF1A5276)),SizedBox(width:12),Text('No upcoming appointment')]):Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Next appointment',style:TextStyle(fontWeight:FontWeight.bold,color:Color(0xFF1A5276))),const SizedBox(height:8),Text(a['date']??'',style:const TextStyle(fontSize:18,fontWeight:FontWeight.bold)),Text('${a['time']??''} • ${a['service']??'Dental care'}'),if(a['doctor']!=null)Text('With ${a['doctor']}',style:const TextStyle(color:Colors.black54))])));}
  Widget _action(IconData i,String t,VoidCallback f)=>Card(child:InkWell(onTap:f,borderRadius:BorderRadius.circular(20),child:Padding(padding:const EdgeInsets.all(18),child:Column(children:[Icon(i,size:30,color:const Color(0xFF1A5276)),const SizedBox(height:8),Text(t,style:const TextStyle(fontWeight:FontWeight.bold))]))));
  Widget _section(String title,dynamic list)=>Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:const TextStyle(fontSize:18,fontWeight:FontWeight.bold)),const SizedBox(height:10),if(list is List && list.isEmpty)const Text('No recent notifications.',style:TextStyle(color:Colors.black45)),if(list is List)for(final n in list.take(3))Card(child:ListTile(leading:const Icon(Icons.notifications_none,color:Color(0xFF1A5276)),title:Text(n['title']??''),subtitle:Text(n['message']??''))) ]);
}
