# Generated by Django 5.1.2 on 2026-08-11 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0006_alter_patient_allergies_alter_patient_registered_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientPortalAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal_pin', models.CharField(help_text='4-6 digit PIN for portal access', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('login_attempts', models.IntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal_access', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Patient Portal Access',
                'verbose_name_plural': 'Patient Portal Access',
            },
        ),
        migrations.CreateModel(
            name='PatientPortalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_logs', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Patient Portal Log',
                'verbose_name_plural': 'Patient Portal Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
