# Generated by Django 5.1.2 on 2026-10-02 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_portal', '0003_patient_portal_features'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='patientconversation',
            new_name='patient_por_patient_5b144f_idx',
            old_name='patient_por_patient_1f8a10_idx',
        ),
        migrations.RenameIndex(
            model_name='patientmessage',
            new_name='patient_por_convers_5ae235_idx',
            old_name='patient_por_convers_3f4a2c_idx',
        ),
        migrations.RenameIndex(
            model_name='patientmessage',
            new_name='patient_por_sender__ea8f0f_idx',
            old_name='patient_por_sender__9d3f91_idx',
        ),
        migrations.RenameIndex(
            model_name='portalnotification',
            new_name='patient_por_patient_d38191_idx',
            old_name='patient_por_patient_8b1d31_idx',
        ),
        migrations.RenameIndex(
            model_name='portalnotification',
            new_name='patient_por_appoint_28b0c0_idx',
            old_name='patient_por_appointm_4e7a22_idx',
        ),
        migrations.RenameIndex(
            model_name='portaloffer',
            new_name='patient_por_is_publ_b4665e_idx',
            old_name='patient_por_is_publ_1e5b9e_idx',
        ),
    ]
