# Generated by Django 5.1.2 on 2026-08-15 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_options_alter_doctor_options_and_more'),
        ('patients', '0006_alter_patient_allergies_alter_patient_registered_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('history', 'History'), ('examination', 'Examination'), ('diagnosis', 'Diagnosis'), ('treatment', 'Treatment Plan'), ('procedure', 'Procedure'), ('prescription', 'Prescription'), ('referral', 'Referral'), ('follow_up', 'Follow Up'), ('general', 'General Note')], default='general', max_length=50)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_notes', to='appointments.appointment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clinical Note',
                'verbose_name_plural': 'Clinical Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DentalChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tooth_number', models.IntegerField(help_text='Universal tooth numbering system (1-32)')),
                ('tooth_name', models.CharField(blank=True, max_length=50, null=True)),
                ('surface', models.CharField(blank=True, choices=[('occlusal', 'Occlusal'), ('mesial', 'Mesial'), ('distal', 'Distal'), ('buccal', 'Buccal'), ('lingual', 'Lingual'), ('incisal', 'Incisal'), ('labial', 'Labial'), ('palatal', 'Palatal')], max_length=20, null=True)),
                ('condition', models.CharField(choices=[('healthy', 'Healthy'), ('decay', 'Decay/Cavity'), ('filling', 'Filling'), ('crown', 'Crown'), ('bridge', 'Bridge'), ('extraction', 'Extraction'), ('implant', 'Implant'), ('root_canal', 'Root Canal'), ('fracture', 'Fracture'), ('missing', 'Missing'), ('wear', 'Wear'), ('stain', 'Stain'), ('other', 'Other')], default='healthy', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dental_charts', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Dental Chart',
                'verbose_name_plural': 'Dental Charts',
                'ordering': ['tooth_number'],
            },
        ),
    ]
