# Generated by Django 5.1.2 on 2026-09-01 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_unique_doctor_slot'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appointment_appoint_d43bd6_idx',
            old_name='appt_date_doc_status_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appointment_patient_49b41f_idx',
            old_name='appt_patient_date_idx',
        ),
    ]
