# Generated by Django 5.1.2 on 2026-08-05 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='patient_photos/'),
        ),
        migrations.CreateModel(
            name='DentalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dental_images/')),
                ('image_type', models.CharField(choices=[('clinical', 'Clinical Photo'), ('xray', 'X-Ray'), ('treatment', 'Treatment Photo'), ('before', 'Before Treatment'), ('after', 'After Treatment'), ('surgery', 'Surgery Photo'), ('other', 'Other')], default='clinical', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dental_images', to='patients.patient')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dental Image',
                'verbose_name_plural': 'Dental Images',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
