# Generated by Django 5.1.2 on 2026-08-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_profile_picture_dentalimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age_years',
            field=models.IntegerField(blank=True, help_text='If date of birth is unknown, enter age in years', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='registered_at',
            field=models.DateTimeField(),
        ),
    ]
