# Generated by Django 5.1.2 on 2026-08-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_age_years_alter_patient_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='previous_surgery',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='surgery_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
