# Generated by Django 5.1.2 on 2026-08-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_dentalimage_id_alter_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='allergies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
