# Generated by Django 5.1.2 on 2026-09-28 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_patientcontactaccessrequest'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='patientcontactaccessrequest',
            new_name='patients_pa_patient_59e50b_idx',
            old_name='patients_pat_patient_1e4a62_idx',
        ),
        migrations.RenameIndex(
            model_name='patientcontactaccessrequest',
            new_name='patients_pa_status_a9df5b_idx',
            old_name='patients_pat_status_0cf65f_idx',
        ),
    ]
