# Generated by Django 5.1.2 on 2026-08-03 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_reminders', models.BooleanField(default=True)),
                ('reminder_hours_before', models.PositiveIntegerField(default=24, help_text='Hours before appointment to send reminder')),
                ('reminder_days_before', models.PositiveIntegerField(default=1, help_text='Days before appointment to send reminder')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('both', 'Both')], default='both', max_length=10)),
                ('email_subject', models.CharField(default="Appointment Reminder - Dora's Dental Gem", max_length=200)),
                ('email_template', models.TextField(default="\nDear {{ patient_name }},\n\nThis is a reminder of your upcoming appointment at Dora's Dental Gem.\n\nAppointment Details:\n- Date: {{ appointment_date }}\n- Time: {{ appointment_time }}\n- Doctor: {{ doctor_name }}\n- Service: {{ service_name }}\n\nPlease arrive 15 minutes before your appointment.\n\nIf you need to reschedule, please call us at {{ clinic_phone }}.\n\nThank you,\nDora's Dental Gem Team\n")),
                ('sms_template', models.TextField(default="Dora's Dental Gem Reminder: {{ patient_name }}, your appointment is on {{ appointment_date }} at {{ appointment_time }} with Dr. {{ doctor_name }}. Call {{ clinic_phone }} to reschedule.")),
                ('twilio_account_sid', models.CharField(blank=True, max_length=200, null=True)),
                ('twilio_auth_token', models.CharField(blank=True, max_length=200, null=True)),
                ('twilio_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Notification Settings',
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=10)),
                ('sent_to', models.CharField(max_length=200)),
                ('subject', models.CharField(blank=True, max_length=500, null=True)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='appointments.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='patients.patient')),
            ],
            options={
                'verbose_name_plural': 'Notification Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
