# Generated by Django 5.1.2 on 2026-09-21 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_staff_notifications_push'),
        ('notifications', '0003_usernotification_pushsubscription'),
    ]

    operations = [
    ]
