# Generated by Django 5.1.2 on 2026-09-28 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_appointment_findings_treatment_done'),
        ('notifications', '0004_merge_20260920_2151'),
        ('patients', '0009_rename_patients_pat_patient_1e4a62_idx_patients_pa_patient_59e50b_idx_and_more'),
    ]

    operations = [

        # ---------------------------------------------------------
        # 1. Rename notification recipient index if it still exists.
        # ---------------------------------------------------------
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='''
                        ALTER INDEX IF EXISTS
                        "notificatio_recipie_5d4c2f_idx"
                        RENAME TO "notificatio_recipie_089876_idx";
                    ''',
                    reverse_sql='''
                        ALTER INDEX IF EXISTS
                        "notificatio_recipie_089876_idx"
                        RENAME TO "notificatio_recipie_5d4c2f_idx";
                    ''',
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='usernotification',
                    new_name='notificatio_recipie_089876_idx',
                    old_name='notificatio_recipie_5d4c2f_idx',
                ),
            ],
        ),

        # ---------------------------------------------------------
        # 2. Remove read_at if it still exists.
        # ---------------------------------------------------------
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='''
                        ALTER TABLE "notifications_usernotification"
                        DROP COLUMN IF EXISTS "read_at" CASCADE;
                    ''',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='usernotification',
                    name='read_at',
                ),
            ],
        ),

        # ---------------------------------------------------------
        # 3. Add patient_id if it does not already exist.
        #
        # Railway already has this column, so don't try to add it
        # again. Also ensure the foreign-key constraint exists.
        # ---------------------------------------------------------
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='''
                        ALTER TABLE "notifications_usernotification"
                        ADD COLUMN IF NOT EXISTS
                        "patient_id" bigint NULL;

                        DO $$
                        BEGIN
                            IF NOT EXISTS (
                                SELECT 1
                                FROM pg_constraint
                                WHERE conname =
                                    'notifications_userno_patient_id_62a3f24c_fk_patients_'
                            ) THEN
                                ALTER TABLE "notifications_usernotification"
                                ADD CONSTRAINT
                                    "notifications_userno_patient_id_62a3f24c_fk_patients_"
                                FOREIGN KEY ("patient_id")
                                REFERENCES "patients_patient" ("id")
                                DEFERRABLE INITIALLY DEFERRED;
                            END IF;
                        END
                        $$;
                    ''',
                    reverse_sql='''
                        ALTER TABLE "notifications_usernotification"
                        DROP CONSTRAINT IF EXISTS
                        "notifications_userno_patient_id_62a3f24c_fk_patients_";

                        ALTER TABLE "notifications_usernotification"
                        DROP COLUMN IF EXISTS "patient_id";
                    ''',
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='usernotification',
                    name='patient',
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='user_notifications',
                        to='patients.patient',
                    ),
                ),
            ],
        ),

        # ---------------------------------------------------------
        # 4. PushSubscription.auth
        # ---------------------------------------------------------
        migrations.AlterField(
            model_name='pushsubscription',
            name='auth',
            field=models.TextField(),
        ),

        # ---------------------------------------------------------
        # 5. PushSubscription.endpoint
        # ---------------------------------------------------------
        migrations.AlterField(
            model_name='pushsubscription',
            name='endpoint',
            field=models.URLField(
                max_length=1000,
                unique=True,
            ),
        ),

        # ---------------------------------------------------------
        # 6. PushSubscription.p256dh
        # ---------------------------------------------------------
        migrations.AlterField(
            model_name='pushsubscription',
            name='p256dh',
            field=models.TextField(),
        ),

        # ---------------------------------------------------------
        # 7. PushSubscription.user_agent
        # ---------------------------------------------------------
        migrations.AlterField(
            model_name='pushsubscription',
            name='user_agent',
            field=models.TextField(
                blank=True,
                default='',
            ),
        ),

        # ---------------------------------------------------------
        # 8. UserNotification.appointment
        # ---------------------------------------------------------
        migrations.AlterField(
            model_name='usernotification',
            name='appointment',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='user_notifications',
                to='appointments.appointment',
            ),
        ),

        # ---------------------------------------------------------
        # 9. UserNotification.notification_type
        # ---------------------------------------------------------
        migrations.AlterField(
            model_name='usernotification',
            name='notification_type',
            field=models.CharField(
                choices=[
                    (
                        'appointment_assigned',
                        'Appointment Assigned',
                    ),
                    (
                        'appointment_completed',
                        'Appointment Completed',
                    ),
                    (
                        'contact_access_request',
                        'Contact Access Request',
                    ),
                    (
                        'contact_access_approved',
                        'Contact Access Approved',
                    ),
                    (
                        'contact_access_denied',
                        'Contact Access Denied',
                    ),
                    (
                        'system',
                        'System',
                    ),
                ],
                default='system',
                max_length=40,
            ),
        ),

        # ---------------------------------------------------------
        # 10. UserNotification.url
        # ---------------------------------------------------------
        migrations.AlterField(
            model_name='usernotification',
            name='url',
            field=models.CharField(
                blank=True,
                default='',
                max_length=500,
            ),
        ),

        # ---------------------------------------------------------
        # 11. Create patient index if it doesn't already exist.
        # ---------------------------------------------------------
        migrations.RunSQL(
            sql='''
                CREATE INDEX IF NOT EXISTS
                "notifications_usernotification_patient_id_62a3f24c"
                ON "notifications_usernotification" ("patient_id");
            ''',
            reverse_sql='''
                DROP INDEX IF EXISTS
                "notifications_usernotification_patient_id_62a3f24c";
            ''',
        ),
    ]