# Generated by Django 5.1.2 on 2026-09-28
#
# Migration history repair:
# The notification models were already created in
# 0003_usernotification_pushsubscription.py. The earlier version of this
# migration attempted to repeat state changes (read_at/patient/index) that
# are already represented correctly by the 0003 migration state, and it used
# PostgreSQL-only SQL that breaks fresh SQLite test databases.
#
# Existing PostgreSQL databases are also already compatible with the current
# model state (patient_id exists and read_at was removed during the previous
# Railway repair). Therefore this migration intentionally performs no
# database/state operation.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "appointments",
            "0009_appointment_findings_treatment_done",
        ),
        (
            "notifications",
            "0004_merge_20260920_2151",
        ),
        (
            "patients",
            "0009_rename_patients_pat_patient_1e4a62_idx_patients_pa_patient_59e50b_idx_and_more",
        ),
    ]

    operations = [
    ]
