# Generated by Django 5.1.2 on 2026-10-03 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_mobile_device_token'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='usernotification',
            new_name='notificatio_recipie_089876_idx',
            old_name='notificatio_recipie_5b7ef9_idx',
        ),
    ]
